version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,sqs,dynambodb,events,iam
      - DEBUG=1
    ports:
      - "4566:4566"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: documents
    ports:
      - "5432:5432"